### ISSUE TITLE
Google sign-in secturity

### ISSUE THREAD

**Issue by ozay17** [KyzaGitHub/Unofficial-Desktop-YouTube-Music#11]
unable to sign to google account due to unrecognized browser

**Comment by KyzaGitHub** [comment]
I'm doing a full rewrite of this that allows for both YouTube and YouTube Music. So this repository is deprecated and will be archived when the rewrite is released.

This problem in the rewrite is solved.

Google sends different pages based on your user agent, so for the account login page it sends `Chrome` as the user agent instead of the usual one when loading them.
